@startuml
'https://plantuml.com/class-diagram

class Plateau{
    + int height;
    + int width;
    - int plateauGrid[][];

    + void Plateau(int height, int width);
    + void printPlateau();
    + boolean isPositionFree(int x, int y);
    + void setPositionOccupied(int x, int y);
    + void setPositionFree(int x, int y);
}

class Rover extends MarsVehicles{
    + int position[];
    + Orientation orientation;
    + Plateau plateau;

    void MarsRover(int x, int y, Orientation orientation);

    + void execute(char command);
    - int[] calculateNewPosition(int command);
    + void printPositionAndOrientation();
}

class MarsVehicles{
    + Plateau plateau;
    + Stack<MarsVehicles> vehicles;
}

enum Orientation{
    N, E, S, W

    - static Orientation[] vals;
    + left();
    + right();
}
@enduml