@startuml
'https://plantuml.com/class-diagram

class Plateau{
    + int topRow;
    + int lastColumn;
    - int plateauGrid[][];

    + Plateau(int topRow, int lastColumn);
    + void printPlateau();
    + boolean isPositionFree(int x, int y);
    + void setPositionOccupied(int x, int y);
    + void setPositionFree(int x, int y);
}

class Rover{
    + int position[];
    + Orientation orientation;
    + Plateau plateau;

    + Rover(int x, int y, Orientation orientation, Plateau plateau);
    + boolean execute(char command);
    + int[] calculateNewPosition();
    + void printPositionAndOrientation();
    + int[] getPosition();
    + Orientation getOrientation();
}
Plateau "1" -> "many" Rover
enum Orientation{
    N, E, S, W
    + Orientation left();
    + Orientation right();
}
@enduml